name:                seat-sorter
version:             0.1.0.0
github:              "jonathanlorimer/seat-sorter"
license:             BSD3
author:              "Jonathan Lorimer"
maintainer:          "jonathan_lorimer@mac.com"
copyright:           "2019 Jonathan Lorimer"

description:         Please see the README on GitHub at <https://github.com/jonathanlorimer/seat-sorter#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- criterion
- directory
- hspec
- hspec-discover
- text
- megaparsec

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  seat-sorter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - seat-sorter

tests:
  seat-sorter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - seat-sorter
